development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bantec_app_development
  pool: 5
  username: hibiking
  password: Toromaru@5513
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bantec_app_test
  pool: 5
  username: hibiking
  password: Toromaru@5513
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  bantec_app_production
  pool: 5
  username: hibiking
  password: Toromaru@5513
  host: localhost
